## Deliverable 3. Create a Travel Itinerary Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [5]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Camacha,PT,77.54,scattered clouds,33.0833,-16.3333,Hotel Porto Santo & Spa
1,3,Itarema,BR,85.44,scattered clouds,-2.9248,-39.9167,"Sea Lounge! Bar, Club & Restaurant"
2,10,Wurzen,DE,75.99,overcast clouds,51.3667,12.7333,Hotel Zur Post
3,24,Kokopo,PG,76.21,light rain,-4.3520,152.2633,Kokopo Beach Bungalow Resort
4,27,Ashqelon,IL,84.81,clear sky,31.6693,34.5715,Leonardo Ashkelon

In [7]:
clean_hotel_df = vacation_df.dropna()
clean_hotel_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Camacha,PT,77.54,scattered clouds,33.0833,-16.3333,Hotel Porto Santo & Spa
1,3,Itarema,BR,85.44,scattered clouds,-2.9248,-39.9167,"Sea Lounge! Bar, Club & Restaurant"
2,10,Wurzen,DE,75.99,overcast clouds,51.3667,12.7333,Hotel Zur Post
3,24,Kokopo,PG,76.21,light rain,-4.3520,152.2633,Kokopo Beach Bungalow Resort
4,27,Ashqelon,IL,84.81,clear sky,31.6693,34.5715,Leonardo Ashkelon
...,...,...,...,...,...,...,...,...
285,723,Sabancuy,MX,87.17,overcast clouds,18.9667,-91.1833,pulpo
286,724,Kijang,KR,76.73,clear sky,35.2442,129.2139,Samyang Beach Villa
287,725,Namatanai,PG,78.21,scattered clouds,-3.6667,152.4333,Seagulls Inn Namatani
288,730,Tabuk,PH,76.39,light rain,17.4189,121.4443,Golden Berries Hotel and Convention
289,731,Coos Bay,US,80.85,haze,43.3665,-124.2179,Best Western Holiday Hotel

In [8]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F<dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [9]:
# 4a. Add a marker layer for each city to the map.
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [76]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = clean_hotel_df.loc[clean_hotel_df["City"] == "Mazamet"]
vacation_end = clean_hotel_df.loc[clean_hotel_df["City"] == "Mazamet"]
vacation_stop1 = clean_hotel_df.loc[clean_hotel_df["City"] == "Montalban"]
vacation_stop2 = clean_hotel_df.loc[clean_hotel_df["City"] == "Hauterive"] 
vacation_stop3 = clean_hotel_df.loc[clean_hotel_df["City"] == "Vierzon"] 
vacation_stop2

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
66,190,Hauterive,FR,75.96,scattered clouds,46.0901,3.4459,Aletti Palace Hotel

In [61]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat","Lng"]].to_numpy()
end = vacation_end[["Lat","Lng"]].to_numpy()
stop1 = vacation_stop1[["Lat","Lng"]].to_numpy()
stop2 = vacation_stop2[["Lat","Lng"]].to_numpy()
stop3 = vacation_stop3[["Lat","Lng"]].to_numpy()
start_coord = (start[0][0], start[0][1])
end_coord = (end[0][0], end[0][1])
stop1_coord = (stop1[0][0], stop1[0][1])
stop2_coord = (stop2[0][0], stop2[0][1])
stop3_coord = (stop3[0][0], stop3[0][1])

In [63]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
direction_layer = gmaps.directions_layer(
        start_coord, end_coord, waypoints=[stop1_coord, stop2_coord, stop3_coord],
        travel_mode="BICYCLING")
fig.add_layer(direction_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [64]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
direction_layer = gmaps.directions_layer(
        start_coord, end_coord, waypoints=[stop1_coord, stop2_coord, stop3_coord],
        travel_mode="DRIVING")
fig.add_layer(direction_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [89]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1 ,vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,594,Mazamet,FR,79.09,clear sky,43.4900,2.3730,La Villa de Mazamet
1,591,Montalban,FR,79.59,scattered clouds,44.0167,1.3500,Abbaye des Capucins Spa & Resort
2,190,Hauterive,FR,75.96,scattered clouds,46.0901,3.4459,Aletti Palace Hotel
3,160,Vierzon,FR,76.55,overcast clouds,47.2101,2.0625,Arche HÃ´tel

In [90]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F<dd>
</dl>
"""
# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations_itinerary = itinerary_df[["Lat", "Lng"]]
locations_itinerary

       Lat     Lng
0  43.4900  2.3730
1  44.0167  1.3500
2  46.0901  3.4459
3  47.2101  2.0625

In [92]:
# 11a. Add a marker layer for each city to the map.
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations_itinerary, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations_itinerary, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))